apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.selectorLabel }}
