replicasCount: 1
fullName: "public-api"
selectorLabel: "public-api"

service:
  port: 80

containers:
  public_api:
    name: public-api
    image: registry.local/public-api
    pullPolicy: Always
    dgraphPort: 8080
    dgraphHost: node-port-dgraph.default.svc.cluster.local

