replicasCount: 1
fullName: "alexstorm-public-api"
selectorLabel: "alexstorm-public-api"

service:
  port: 80
containers:
  public_api:
    name: alexstorm-public-api
    image: registry.alexstorm.solenopsys.org/alexstorm-public-api
    pullPolicy: Always
    dgraphPort: 8080
    dgraphHost: solenopsys-ds-dgraph.default.svc.cluster.local

